name: "Run action"
on: [workflow_dispatch]

jobs:
  run_tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: ls ${{ github.workspace }}

      - name: Extract log
        run: |
          chmod +x ./export_uas.sh
          ./export_uas.sh ./testresult.xcresult \
          [ -d ./output/uas.log ] && echo "Log extracted succesfully"